"use client"

import type { ReactNode } from "react"
import Image from "next/image"
import Link from "next/link"
import { useMemo, useState } from "react"
import { ArrowRight, Check, ChevronRight, Clock3, Mail, MapPin, Phone, ShieldCheck, SunMedium, Wrench, Zap } from "lucide-react"
import ContactForm from "./ContactForm"
import QuoteForm from "@/components/quote/QuoteForm"
import ProductCard from "@/components/home/products/ProductCard"
import GalleryCard from "@/components/gallery/GalleryCard"
import { catalogueBrands, catalogueProducts } from "@/components/catalogue/catalogueData"
import { electricalCategories, insights, projects, services, solarCategories } from "./data"
import { PageMotion, Reveal } from "./PageMotion"

type HeroProps = { eyebrow: string; title: ReactNode; description: string; image: string; compact?: boolean }

export function PageHero({ eyebrow, title, description, image, compact }: HeroProps) {
  return (
    <section className={`page-hero-new ${compact ? "page-hero-new--compact" : ""}`}>
      <Image src={image} alt="" fill priority sizes="100vw" />
      <div className="page-hero-new__shade" />
      <div className="page-hero-new__line" />
      <div className="shell page-hero-new__content">
        <Reveal><span className="eyebrow eyebrow--lime">{eyebrow}</span><h1>{title}</h1><p>{description}</p></Reveal>
      </div>
    </section>
  )
}

function SectionHeading({ eyebrow, title, description, action }: { eyebrow: string; title: ReactNode; description?: string; action?: { label: string; href: string } }) {
  return <Reveal className="section-heading-rich"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{description && <p>{description}</p>}{action && <Link href={action.href} className="text-link">{action.label}<ArrowRight size={17} /></Link>}</Reveal>
}

function ImageStory({ image, alt, eyebrow, title, children, reverse = false }: { image: string; alt: string; eyebrow: string; title: ReactNode; children: ReactNode; reverse?: boolean }) {
  return <section className="section"><div className={`shell image-story ${reverse ? "image-story--reverse" : ""}`}><Reveal className="image-story__visual"><Image src={image} alt={alt} fill sizes="(max-width: 840px) 100vw, 48vw" /><span className="image-story__corner" /></Reveal><Reveal className="image-story__copy"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{children}</Reveal></div></section>
}

const approach = [
  ["Listen closely", "We begin by understanding the space, the people who use it, and the problem that needs solving."],
  ["Plan with purpose", "We shape a practical route forward, balancing safety, performance, budget, and long-term confidence."],
  ["Deliver with care", "Our work is organised around clear communication, quality products, and disciplined installation."],
  ["Stay available", "After completion, we remain a useful partner for maintenance, upgrades, questions, and future ideas."],
]

function ApproachSection({ title = <>A process built around <em>confidence.</em></> }: { title?: ReactNode }) {
  return <section className="section approach-section"><div className="shell"><SectionHeading eyebrow="Our approach" title={title} description="The strongest systems are not rushed. They are understood, planned, and supported long after the first switch is turned on." /><ol className="approach-grid">{approach.map(([heading, copy], index) => <Reveal key={heading} delay={index * .06}><li className="border-motion"><span>0{index + 1}</span><h3>{heading}</h3><p>{copy}</p><i /></li></Reveal>)}</ol></div></section>
}

export function AboutExperience() {
  return <PageMotion><PageHero eyebrow="About Dantown" title={<>Built for safer, smarter <em>everyday power.</em></>} description="We are a Kitale-based electrical and energy solutions company committed to the practical needs of homes, businesses, and institutions." image="/image/about/shop.png" />
    <ImageStory image="/image/about/shop.webp" alt="Dantown Electrical solutions centre" eyebrow="Our purpose" title={<>Reliable energy changes what is <em>possible.</em></>}><p>Dantown Electrical is committed to delivering dependable electrical and solar energy solutions that improve everyday life, support businesses, and contribute to a more sustainable future.</p><p>We combine technical expertise, quality products, and professional service so our customers can make safer, smarter, more efficient energy choices.</p><Link href="/contact" className="button button--blue">Talk to our team <ArrowRight size={17} /></Link></ImageStory>
    <section className="section section--soft"><div className="shell"><SectionHeading eyebrow="What we believe" title={<>Progress should feel <em>practical.</em></>} description="Our mission and vision help keep every recommendation grounded in what matters: a safer, more reliable, more useful energy future." /><div className="mission-grid-rich"><Reveal><article className="border-motion"><span className="eyebrow">Mission</span><h3>Make dependable energy solutions easier to access.</h3><p>We translate real requirements into the right electrical and energy system, with clear advice from the first question to ongoing support.</p><Image src="/image/gallery/Electrical.webp" alt="Electrical work in progress" fill sizes="(max-width: 840px) 100vw, 50vw" /></article></Reveal><Reveal delay={.08}><article className="border-motion"><span className="eyebrow">Vision</span><h3>Help build a more reliable, sustainable energy future.</h3><p>Our work is rooted in useful technology, responsible thinking, and service that helps people move forward with confidence.</p><Image src="/image/gallery/Solar.webp" alt="Solar panels supporting clean energy" fill sizes="(max-width: 840px) 100vw, 50vw" /></article></Reveal></div></div></section>
    <section className="section"><div className="shell values-layout"><Reveal><span className="eyebrow">What guides us</span><h2>Work we can stand <em>behind.</em></h2><p>Every project is a chance to demonstrate the kind of company we want Dantown to be: capable, clear, dependable, and deeply invested in the people we serve.</p></Reveal><div className="values-detail-grid">{[['Reliability', 'Clear, consistent service and systems built to work when they are needed most.'], ['Innovation', 'Modern solutions selected because they improve everyday outcomes, not because they are complicated.'], ['Quality', 'Careful recommendations, durable equipment, and craftsmanship that respects the details.'], ['Integrity', 'Honest guidance in language you can understand before you commit to a decision.'], ['Customer focus', 'A practical understanding of what each home, business, and community is trying to achieve.'], ['Sustainability', 'Clean-energy thinking that supports a more resilient future for Kitale and beyond.']].map(([title, copy], index) => <Reveal key={title} delay={index * .04}><article className="border-motion"><span>0{index + 1}</span><Check size={19} /><h3>{title}</h3><p>{copy}</p></article></Reveal>)}</div></div></section>
    <ApproachSection title={<>The Dantown standard, from first <em>conversation to support.</em></>} />
    <QuoteBanner /></PageMotion>
}

export function ServicesExperience() {
  return <PageMotion><PageHero eyebrow="Our expertise" title={<>Electrical and energy solutions, <em>thoughtfully delivered.</em></>} description="Professional services designed for the needs of homes, businesses, and institutions across Kitale and beyond." image="/image/service/service1.jpeg" />
    <section className="section"><div className="shell"><SectionHeading eyebrow="What we do" title={<>One dependable team for <em>everyday power.</em></>} description="Whether you are planning something new, solving an urgent issue, or considering clean energy, our services start with your goals and end with a practical path forward." /><div className="service-list-rich">{services.map((service, index) => { const Icon = service.icon; return <Reveal key={service.title} delay={index * .03}><article className="service-list-card border-motion"><div className="service-list-card__image"><Image src={service.image} alt={service.title} fill sizes="(max-width: 840px) 100vw, 38vw" /></div><div className="service-list-card__body"><span className="icon-chip"><Icon size={22} /></span><span className="service-list-card__number">0{index + 1}</span><h3>{service.title}</h3><p>{service.description}</p><ul>{service.includes.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul><Link href={service.href} className="text-link">Explore solution <ArrowRight size={17} /></Link></div></article></Reveal> })}</div></div></section>
    <ImageStory image="/image/gallery/Commercial.webp" alt="Commercial electrical solution" eyebrow="More than installation" title={<>A partner for the work <em>behind the walls.</em></>} reverse><p>The equipment people see is only part of the story. Good electrical and energy work considers safety, distribution, maintenance access, energy performance, and how the space will change over time.</p><div className="check-list-large">{['Advice based on your actual priorities', 'Attention to safety and future maintenance', 'Clear scope before work begins', 'Support for upgrades and next-stage projects'].map((item) => <span key={item}><ShieldCheck size={18} />{item}</span>)}</div></ImageStory>
    <ApproachSection title={<>A calmer way to move from <em>need to solution.</em></>} />
    <QuoteBanner /></PageMotion>
}

export function SolutionExperience({ type }: { type: "solar" | "electrical" }) {
  const isSolar = type === "solar"
  const categories = isSolar ? solarCategories : electricalCategories
  const title = isSolar ? <>Clean energy for a <em>smarter future.</em></> : <>Safe, dependable electrical systems <em>that work hard.</em></>
  const description = isSolar ? "From a home solar system to commercial energy planning, we make the transition to renewable energy feel clear and achievable." : "From new installations to maintenance and upgrades, we bring a careful, professional approach to the power behind your space."
  const Icon = isSolar ? SunMedium : Zap
  const image = isSolar ? "/image/gallery/Solar.webp" : "/image/gallery/Electrical.webp"
  const benefits = isSolar ? [['Resilience', 'More confidence in the power behind your day-to-day life and work.'], ['Efficiency', 'A system designed around the energy you actually use.'], ['Clarity', 'Practical advice before you decide how to invest.'], ['Care', 'Maintenance and support that helps your system keep performing.']] : [['Safety', 'The right protection and installation practice from the start.'], ['Performance', 'Electrical systems that serve the way a space is used.'], ['Adaptability', 'Thoughtful foundations for changes, growth, and upgrades.'], ['Support', 'Professional assistance when a system needs attention.']]
  return <PageMotion><PageHero eyebrow={isSolar ? "Solar solutions" : "Electrical solutions"} title={title} description={description} image={image} />
    <section className="section"><div className="shell solution-lead-rich"><Reveal><span className="icon-chip"><Icon size={22} /></span><span className="eyebrow">A solution built around you</span><h2>{isSolar ? "Make energy more independent." : "Get the fundamentals right."}</h2></Reveal><Reveal delay={.08}><p>{isSolar ? "A well-designed solar solution can support your comfort, help manage electricity costs, and give you more confidence in your day-to-day power. We will help you understand the options before you choose." : "Great electrical work is not just about cables and fittings. It is planning, protection, practical design, and an installation that makes the space safer and easier to use."}</p><Link className="text-link" href="/contact">Discuss your requirements <ArrowRight size={17} /></Link></Reveal></div></section>
    <section className="section section--soft"><div className="shell"><SectionHeading eyebrow={isSolar ? "Solar made useful" : "Electrical work, considered"} title={<>Every detail has a role in the <em>whole system.</em></>} description="Explore the elements we can bring together around your requirements." /><div className="solution-category-grid-rich">{categories.map(({ title: category, icon: CategoryIcon }, index) => <Reveal key={category} delay={index * .04}><article id={category === "Battery storage" ? "backup" : category === "Lighting design" ? "lighting" : category === "Inspection & maintenance" ? "maintenance" : undefined} className="border-motion"><span>0{index + 1}</span><CategoryIcon size={25} /><h3>{category}</h3><p>{isSolar ? "Planned to suit your property, power needs, and energy goals." : "Delivered with attention to safety, usability, and lasting performance."}</p></article></Reveal>)}</div></div></section>
    <ImageStory image={isSolar ? "/image/home/solarcomplet.webp" : "/image/home/electrical.webp"} alt={isSolar ? "Solar panel installation" : "Electrical installation"} eyebrow="Designed to last" title={isSolar ? <>A solar system should feel like <em>freedom, not complexity.</em></> : <>Power should simply work — safely, <em>every day.</em></>}>{isSolar ? <p>We help turn panels, batteries, inverters, and your everyday needs into a system you can understand. The goal is not just generation; it is useful, reliable power that supports the life you are building.</p> : <p>From first-fix wiring to lighting, protection, and troubleshooting, the strength of an electrical installation is found in the details people may never see — but rely on all the time.</p>}<div className="check-list-large">{benefits.map(([heading, copy]) => <span key={heading}><Check size={18} /><b>{heading}:</b> {copy}</span>)}</div></ImageStory>
    <ApproachSection title={<>A better energy decision starts with <em>a good conversation.</em></>} />
    <QuoteBanner /></PageMotion>
}

export function ProjectsExperience() {
  const [selected, setSelected] = useState("All")
  const filtered = useMemo(() => selected === "All" ? projects : projects.filter((project) => project.category === selected), [selected])
  const categories = ["All", "Solar", "Electrical", "Lighting", "Commercial", "Residential"]
  return <PageMotion><PageHero eyebrow="Our projects" title={<>Real spaces. Reliable <em>solutions.</em></>} description="Explore the kinds of solar, electrical, lighting, and backup projects Dantown Electrical is ready to support." image="/image/gallery/Commercial.webp" />
    <section className="section projects-intro"><div className="shell"><SectionHeading eyebrow="Work that matters" title={<>From a single improvement to a <em>complete system.</em></>} description="Every project begins with context. We consider the people, the site, the present need, and what the future may require." /><Reveal className="projects-intro__visual"><Image src="/image/gallery/Gallary.webp" alt="A selection of Dantown Electrical work" fill sizes="100vw" /><div><span className="eyebrow eyebrow--lime">Built around real needs</span><h3>Projects should leave a space safer, more useful, and ready for what comes next.</h3></div></Reveal></div></section>
    <section className="section section--soft"><div className="shell"><div className="project-filter" aria-label="Filter projects">{categories.map((category) => <button onClick={() => setSelected(category)} className={selected === category ? "is-active" : ""} key={category}>{category}</button>)}</div><div className="portfolio-grid-rich">{filtered.map((project, index) => <Reveal key={project.title} delay={index * .04}><article className="portfolio-card border-motion"><div className="portfolio-card__image"><Image src={project.image} alt={project.title} fill sizes="(max-width: 840px) 100vw, 50vw" /></div><div className="portfolio-card__body"><span>{project.category} <i /> {project.location}</span><h3>{project.title}</h3><p>{project.description}</p><Link href="/contact" className="card-link">Ask about a similar project <ArrowRight size={16} /></Link></div></article></Reveal>)}</div></div></section>
    <ImageStory image="/image/gallery/WaterPump.webp" alt="Solar water pumping solution" eyebrow="Beyond the portfolio" title={<>The right project is a <em>relationship, not a handover.</em></>} reverse><p>A completed installation is the beginning of a system&apos;s working life. We think about support, future upgrades, energy habits, and the questions that appear once people begin using their new solution.</p><Link href="/contact" className="button button--blue">Start your own project <ArrowRight size={17} /></Link></ImageStory>
    <ApproachSection title={<>The same care, whether the brief is <em>small or ambitious.</em></>} />
    <QuoteBanner /></PageMotion>
}

export function InsightsExperience() {
  return <PageMotion><PageHero eyebrow="Insights" title={<>Better questions lead to <em>better energy choices.</em></>} description="Helpful, plain-language guides from Dantown Electrical on solar, safety, maintenance, and using power more wisely." image="/image/blog/bloger.webp" compact />
    <section className="section"><div className="shell featured-insight"><Reveal className="featured-insight__image"><Image src="/image/blog/smartsolar.webp" alt="Solar technology insight" fill sizes="(max-width: 840px) 100vw, 55vw" /></Reveal><Reveal className="featured-insight__copy"><span className="eyebrow">Featured guidance</span><h2>Start with what your power needs to <em>do for you.</em></h2><p>A better system begins with a better brief. Before comparing equipment, it helps to understand your priorities: essential loads, daily routines, growth plans, safety concerns, and the role you want energy to play.</p><Link href="/contact" className="text-link">Ask a practical question <ArrowRight size={17} /></Link></Reveal></div></section>
    <section className="section section--soft"><div className="shell"><SectionHeading eyebrow="Explore the essentials" title={<>Useful ideas for homes, teams, and <em>growing businesses.</em></>} description="These upcoming articles are designed to help you approach energy decisions with more confidence." /><div className="insights-page-grid-rich">{[...insights, ...insights].map((insight, index) => <Reveal key={`${insight.title}-${index}`} delay={(index % 3) * .05}><article className="article-card border-motion"><div className="article-card__image"><Image src={insight.image} alt="" fill sizes="(max-width: 840px) 100vw, 33vw" /></div><div><span>{insight.category} <i /> {insight.readingTime}</span><h3>{index < 3 ? insight.title : `${insight.title}: a practical checklist`}</h3><p>{insight.description}</p><button className="card-link" type="button">Coming soon <ChevronRight size={16} /></button></div></article></Reveal>)}</div></div></section>
    <ImageStory image="/image/blog/tech.webp" alt="Technology and energy planning" eyebrow="Learn with Dantown" title={<>Good information gives you <em>room to choose well.</em></>} reverse><p>We are building this resource to make electrical and solar decisions feel less technical and more useful. Explore the ideas, save the questions, and bring them to our team when you are ready.</p><Link href="/contact" className="button button--blue">Talk to an expert <ArrowRight size={17} /></Link></ImageStory>
    <QuoteBanner /></PageMotion>
}

export function BrandsExperience() {
  return <PageMotion><PageHero eyebrow="Brands & quality" title={<>Quality is in the details you <em>choose first.</em></>} description="Explore a selection of trusted electrical, lighting, power, and security product brands available through Dantown Electrical." image="/image/brands/Brand.webp" />
    <ImageStory image="/image/brands/Product.webp" alt="Electrical product selection" eyebrow="Thoughtful sourcing" title={<>The right component protects the <em>whole solution.</em></>}><p>From a compact home upgrade to a larger commercial installation, the quality of each component influences safety, performance, reliability, and the service life of the system around it.</p><p>We help customers make product decisions with the wider installation in mind — not as isolated purchases.</p><Link href="/contact" className="button button--blue">Ask about a solution <ArrowRight size={17} /></Link></ImageStory>
    <section className="section section--soft"><div className="shell"><SectionHeading eyebrow="Our brand library" title={<>Names recognised for <em>performance.</em></>} description="This is a product brand showcase, not a claim of exclusive representation. Availability and suitability can be confirmed directly with our team." /><div className="brand-grid-rich">{catalogueBrands.map((brand, index) => <Reveal key={brand.id} delay={(index % 4) * .04}><article className="brand-card border-motion"><div>{brand.logo ? <Image src={brand.logo} alt={`${brand.name} logo`} fill sizes="(max-width: 580px) 50vw, 20vw" /> : <strong>{brand.name}</strong>}</div><span>Available by request</span><h3>{brand.name}</h3></article></Reveal>)}</div></div></section>
    <section className="section"><div className="shell brand-principles"><SectionHeading eyebrow="Why it matters" title={<>Product choices should support the <em>long view.</em></>} /><div>{[['Compatibility', 'Equipment should work together as part of a considered electrical or energy system.'], ['Safety', 'Correct, well-specified components help protect people, property, and performance.'], ['Support', 'When you need a repair, upgrade, or future extension, sound product choices make the next step easier.']].map(([heading, copy], index) => <Reveal key={heading} delay={index * .06}><article className="border-motion"><span>0{index + 1}</span><ShieldCheck size={22} /><h3>{heading}</h3><p>{copy}</p></article></Reveal>)}</div></div></section>
    <QuoteBanner /></PageMotion>
}

export function ProductsExperience() {
  const [selectedCategory, setSelectedCategory] = useState("All")
  const categories = ["All", ...Array.from(new Set(catalogueProducts.map((product) => product.category)))]
  const filteredProducts = selectedCategory === "All" ? catalogueProducts : catalogueProducts.filter((product) => product.category === selectedCategory)

  return <PageMotion><PageHero eyebrow="Product catalogue" title={<>Products for the work <em>ahead.</em></>} description="Browse electrical, lighting, solar, backup, tools, pumping, and security products available through Dantown Electrical." image="/image/brands/Product.webp" />
    <section className="section section--soft"><div className="shell"><SectionHeading eyebrow="Browse the catalogue" title={<>Find the right parts for your <em>next project.</em></>} description="Product availability and pricing can change. Select a product to request a current quote from our team." /><div className="catalogue-filter" aria-label="Filter catalogue products">{categories.map((category) => <button key={category} type="button" className={selectedCategory === category ? "is-active" : ""} onClick={() => setSelectedCategory(category)}>{category}</button>)}</div><div className="catalogue-grid">{filteredProducts.map((product) => <ProductCard key={product.id} product={product} />)}</div></div></section>
    <QuoteBanner /></PageMotion>
}

const galleryItems = [
  { id: "electrical-installation", title: "Electrical installation", category: "Electrical", image: "/image/home/electrical.webp", images: ["/image/home/electrical.webp", "/image/gallery/Electrical.webp", "/image/gallery/Commercial.webp"] as [string, string, string] },
  { id: "solar-systems", title: "Solar systems", category: "Solar", image: "/image/gallery/Solar.webp", images: ["/image/gallery/Solar.webp", "/image/home/solarcomplet.webp", "/image/product/solar-panel.webp"] as [string, string, string] },
  { id: "lighting-solutions", title: "Lighting solutions", category: "Lighting", image: "/image/home/lighting.webp", images: ["/image/home/lighting.webp", "/image/gallery/Lighting.webp", "/image/product/led-bulb.webp"] as [string, string, string] },
  { id: "security-systems", title: "Security systems", category: "Security", image: "/image/gallery/Security.webp", images: ["/image/gallery/Security.webp", "/image/home/security.webp", "/image/product/security-light.webp"] as [string, string, string] },
  { id: "water-pumping", title: "Water pumping", category: "Water & energy", image: "/image/gallery/WaterPump.webp", images: ["/image/gallery/WaterPump.webp", "/image/home/solarcomplet.webp", "/image/gallery/Solar.webp"] as [string, string, string] },
  { id: "commercial-projects", title: "Commercial projects", category: "Projects", image: "/image/gallery/Commercial.webp", images: ["/image/gallery/Commercial.webp", "/image/gallery/Electrical.webp", "/image/gallery/Gallary.webp"] as [string, string, string] },
]

export function GalleryExperience() {
  return <PageMotion><PageHero eyebrow="Gallery" title={<>A closer look at <em>the work.</em></>} description="Move across each image to explore electrical, solar, lighting, security, and water solutions from Dantown." image="/image/gallery/Gallary.webp" />
    <section className="section section--soft"><div className="shell"><SectionHeading eyebrow="Explore our work" title={<>Solutions made for <em>real spaces.</em></>} description="Each gallery card contains three views. Move your cursor across a card, or swipe across it on a touch screen." /><div className="interactive-gallery-grid">{galleryItems.map((item) => <article className="interactive-gallery-card" key={item.id}><GalleryCard item={item} /><div className="interactive-gallery-card__body"><span>{item.category}</span><h3>{item.title}</h3></div></article>)}</div></div></section><QuoteBanner /></PageMotion>
}

export function QuoteExperience() {
  return <PageMotion><PageHero eyebrow="Get a quote" title={<>A better project starts with a <em>clear brief.</em></>} description="Tell us what you are planning and our team will use the details to prepare the most useful next step." image="/image/requestquote/RequestQuote.webp" compact />
    <section className="section"><div className="shell quote-layout-rich"><Reveal className="quote-intro-rich"><span className="eyebrow">Let&apos;s build</span><h2>Bring your next <em>idea to life.</em></h2><p>Whether you are exploring solar, planning an electrical installation, improving lighting, or looking for reliable backup power, a clear quotation begins with understanding the project.</p><div>{[['A solution shaped around your needs', ShieldCheck], ['Professional technical thinking', Zap], ['Quality-focused recommendations', Check], ['Support after the first conversation', Wrench]].map(([item, Icon]) => { const PointIcon = Icon as typeof ShieldCheck; return <span key={item as string}><PointIcon size={18} />{item as string}</span> })}</div><Image src="/image/project/project1.webp" alt="Dantown Electrical project" fill sizes="(max-width: 840px) 100vw, 46vw" /></Reveal><Reveal delay={.08} className="quote-form-panel border-motion"><span className="eyebrow">Project details</span><h2>Request your <em>quote.</em></h2><p>The more you can share, the more useful our response can be. Fields marked by your browser as required need to be completed first.</p><QuoteForm /></Reveal></div></section>
    <ImageStory image="/image/gallery/Commercial.webp" alt="Commercial electrical solution" eyebrow="What follows" title={<>A quotation is the start of a <em>thoughtful conversation.</em></>} reverse><p>Once your request reaches our team, we review the requirements, identify questions that matter, and help clarify the route forward. Some projects may need a site assessment before final scope and pricing are confirmed.</p><Link href="/services" className="button button--blue">Explore services <ArrowRight size={17} /></Link></ImageStory>
    <ApproachSection title={<>We turn your details into a <em>practical path forward.</em></>} />
  </PageMotion>
}

export function ContactExperience() {
  return <PageMotion><PageHero eyebrow="Contact Dantown" title={<>Let&apos;s find the right <em>next step.</em></>} description="Tell us what you are planning, fixing, or exploring. Our team will help you turn the details into a practical solution." image="/image/contact/Contact.webp" compact />
    <section className="section"><div className="shell contact-layout-rich"><Reveal className="contact-details"><span className="eyebrow">Get in touch</span><h2>Here when you need <em>clear advice.</em></h2><p>Reach out by phone, email, or inquiry form. We&apos;ll make sure the right person understands what you need.</p><div><a href="https://maps.google.com/?q=Kitale%2C+Kenya" target="_blank" rel="noreferrer"><MapPin size={20} /><span><b>Visit us</b>Kitale, Kenya</span></a><a href="tel:+254745917655"><Phone size={20} /><span><b>Call us</b>+254 745 917 655</span></a><a href="mailto:dantownelectrical@gmail.com"><Mail size={20} /><span><b>Email us</b>dantownelectrical@gmail.com</span></a><span><Clock3 size={20} /><span><b>Opening hours</b>Monday – Saturday · 8:00 AM – 5:00 PM</span></span></div><div className="contact-details__image"><Image src="/image/gallery/Lighting.webp" alt="Dantown lighting project" fill sizes="(max-width: 840px) 100vw, 36vw" /></div></Reveal><Reveal delay={.08} className="contact-form-panel border-motion"><span className="eyebrow">Send an inquiry</span><h2>Tell us about <em>your project.</em></h2><p>Share the essentials — what you need, where it is, and any deadline or concern. We&apos;ll come back with the most useful next step.</p><ContactForm /></Reveal></div></section>
    <ApproachSection title={<>Here is what happens after <em>you reach out.</em></>} />
    <QuoteBanner /></PageMotion>
}

export function LegalExperience({ type }: { type: "privacy" | "terms" }) {
  const isPrivacy = type === "privacy"
  const title = isPrivacy ? "Privacy, with clarity." : "Terms of use, made clear."
  const description = isPrivacy ? "How Dantown Electrical handles the information you choose to share with us." : "The simple terms that guide use of the Dantown Electrical website."
  const sections = isPrivacy ? [["Information you share", "When you contact us, we may collect details such as your name, phone number, email address, service interest, and message so we can respond to your inquiry."], ["How we use it", "We use your information only to communicate with you, understand your request, prepare relevant service advice, and improve the way we support customers."], ["Keeping information secure", "We take reasonable steps to protect the information you share. Any future form integrations will be selected and configured with customer privacy in mind."], ["Your choices", "You can ask us to update or remove the personal information you have shared by contacting Dantown Electrical directly."]] : [["Using this website", "This website provides general information about Dantown Electrical and its services. We aim to keep it clear and current, but service availability and final recommendations may depend on a site assessment."], ["Requests and quotations", "An inquiry or quotation request does not create a contract. Project scope, pricing, timelines, and technical specifications are confirmed directly with our team."], ["Website content", "The content, visuals, and Dantown Electrical brand materials on this website may not be reused without permission."], ["Contact", "If you have a question about these terms or the website, please contact our team in Kitale, Kenya."]]
  return <PageMotion><PageHero eyebrow={isPrivacy ? "Privacy policy" : "Terms of use"} title={title} description={description} image={isPrivacy ? "/image/gallery/Solar.webp" : "/image/gallery/Electrical.webp"} compact /><section className="section"><div className="shell legal-layout-rich"><Reveal><p className="legal-intro">Last updated: September 2026. We&apos;ve written this information in plain language so it is easy to understand.</p></Reveal>{sections.map(([heading, copy], index) => <Reveal key={heading} delay={index * .05}><article className="border-motion"><span>0{index + 1}</span><h2>{heading}</h2><p>{copy}</p></article></Reveal>)}</div></section></PageMotion>
}

export function QuoteBanner() {
  return <section className="section cta-section"><div className="shell cta-panel border-motion"><div><span className="eyebrow eyebrow--lime">Start a conversation</span><h2>Ready to power <em>your future?</em></h2><p>Our team is ready to help you explore the right electrical or energy solution.</p></div><div className="cta-panel__actions"><Link href="/request-quote" className="button button--lime">Get a quote <ArrowRight size={17} /></Link><Link href="/contact" className="button button--glass">Contact us</Link></div></div></section>
}
