"use client"

import type { ReactNode } from "react"
import Image from "next/image"
import Link from "next/link"
import { ArrowRight, Check, ChevronRight, MessageCircle, MoveUpRight, Quote, ShieldCheck, Sparkles, SunMedium, Users, Zap } from "lucide-react"
import { motion } from "framer-motion"
import { insights, projects, services, solarCategories } from "./data"
import { PageMotion } from "./PageMotion"

const fadeUp = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.15 }, transition: { duration: 0.55 } }

function SectionIntro({ eyebrow, title, description, action }: { eyebrow: string; title: ReactNode; description?: string; action?: { label: string; href: string } }) {
  return <div className="section-intro"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{description && <p>{description}</p>}{action && <Link href={action.href} className="text-link">{action.label}<ArrowRight size={17} /></Link>}</div>
}

export default function HomeExperience() {
  return <PageMotion>
    <section className="home-hero">
      <Image className="home-hero__image" src="/image/home/solarcomplet.webp" alt="Solar panels providing clean energy in Kenya" fill priority sizes="100vw" />
      <div className="home-hero__overlay" /><div className="home-hero__grid" />
      <div className="shell home-hero__content">
        <motion.div {...fadeUp} className="hero-copy"><p className="hero-eyebrow"><span /> Dantown Electrical · Kitale, Kenya</p><h1>Powering Kitale.<br /><em>Building a brighter future.</em></h1><p className="hero-description">Reliable electrical and solar solutions for every home, business, and community — delivered with care, technical skill, and a clear commitment to quality.</p><div className="hero-buttons"><Link href="/services" className="button button--lime">Explore our services <ArrowRight size={17} /></Link><Link href="/contact" className="button button--glass"><MessageCircle size={17} /> Talk to an expert</Link></div></motion.div>
        <div className="hero-orbits" aria-hidden="true"><div className="hero-orbit hero-orbit--one"><SunMedium size={20} /><span><b>Solar energy</b>Clean, reliable power</span></div><div className="hero-orbit hero-orbit--two"><Zap size={20} /><span><b>Electrical solutions</b>Professional service</span></div><div className="hero-orbit hero-orbit--three"><ShieldCheck size={20} /><span><b>Expert support</b>Here for the long run</span></div></div>
      </div><a className="hero-scroll" href="#about-preview">Discover Dantown <span /></a>
    </section>

    <section className="trust-bar" aria-label="Dantown Electrical commitments"><div className="shell trust-grid">{[['Kitale-based', 'Local understanding'], ['Solar + electrical', 'Connected expertise'], ['Tailored advice', 'Solutions that fit'], ['Ongoing support', 'Beyond installation']].map(([value, label]) => <div key={value}><strong>{value}</strong><span>{label}</span></div>)}</div></section>

    <section className="section" id="about-preview"><div className="shell about-preview"><motion.div {...fadeUp} className="about-preview__visual"><Image src="/image/about/shop.webp" alt="Dantown Electrical team and solutions centre" fill sizes="(max-width: 780px) 100vw, 48vw" /><div className="image-note"><Sparkles size={17} /><span>Reliable power starts with a thoughtful plan.</span></div></motion.div><motion.div {...fadeUp} className="about-preview__content"><span className="eyebrow">About Dantown</span><h2>Powering communities through <em>reliable energy.</em></h2><p>Dantown Electrical brings together practical electrical expertise, quality products, and professional service to help homes and organisations create safer, smarter, more efficient systems.</p><div className="value-list">{['Reliability', 'Innovation', 'Quality', 'Integrity', 'Customer focus'].map((value) => <span key={value}><Check size={16} />{value}</span>)}</div><Link href="/about" className="button button--blue">Learn more about us <ArrowRight size={17} /></Link></motion.div></div></section>

    <section className="section section--soft"><div className="shell"><SectionIntro eyebrow="Our expertise" title={<>Professional solutions for the way you <em>live and work.</em></>} description="From electrical installations to renewable energy systems, every solution begins with understanding what you actually need." action={{ label: "View all services", href: "/services" }} /><div className="service-grid">{services.map((service, index) => { const Icon = service.icon; return <motion.article {...fadeUp} transition={{ duration: .5, delay: index * .04 }} className="service-card" key={service.title}><div className="service-card__top"><span className="icon-chip"><Icon size={22} /></span><span>0{index + 1}</span></div><h3>{service.title}</h3><p>{service.description}</p><Link href={service.href} className="card-link">Learn more <ArrowRight size={16} /></Link></motion.article> })}</div></div></section>

    <section className="section solar-feature"><div className="shell solar-feature__grid"><motion.div {...fadeUp} className="solar-feature__copy"><span className="eyebrow eyebrow--lime">Solar solutions</span><h2>Clean energy for a <em>smarter future.</em></h2><p>From residential systems to commercial power solutions, we help you improve energy reliability, manage costs, and make a confident move toward renewable energy.</p><div className="solar-category-grid">{solarCategories.map(({ title, icon: Icon }) => <span key={title}><Icon size={16} />{title}</span>)}</div><Link href="/solar-solutions" className="button button--lime">Start your solar journey <ArrowRight size={17} /></Link></motion.div><motion.div {...fadeUp} className="solar-feature__image"><Image src="/image/gallery/Solar.webp" alt="Solar installation by Dantown Electrical" fill sizes="(max-width: 780px) 100vw, 48vw" /><div className="solar-feature__badge"><SunMedium size={24} /><strong>Clean energy</strong><span>Designed around you</span></div></motion.div></div></section>

    <section className="section why-section"><div className="shell"><SectionIntro eyebrow="The Dantown difference" title={<>Why choose <em>Dantown Electrical?</em></>} /><div className="why-grid">{[['Trusted expertise', 'Professional electrical and solar thinking for informed decisions.', Zap], ['Quality solutions', 'Reliable systems and equipment selected with care.', ShieldCheck], ['Professional service', 'Thoughtful workmanship and clear communication from start to finish.', Users], ['Local understanding', 'Based in Kitale, with an eye on the needs of our community.', Sparkles]].map(([title, copy, Icon]) => { const ItemIcon = Icon as typeof Zap; return <motion.article {...fadeUp} className="why-card" key={title as string}><ItemIcon size={23} /><h3>{title as string}</h3><p>{copy as string}</p></motion.article> })}</div></div></section>

    <section className="section section--soft"><div className="shell"><SectionIntro eyebrow="Selected work" title={<>Solutions designed for <em>real life.</em></>} description="A snapshot of the electrical and energy projects we can plan, install, and support." action={{ label: "Explore projects", href: "/projects" }} /><div className="project-preview-grid">{projects.slice(0, 3).map((project, index) => <motion.article {...fadeUp} transition={{ duration: .5, delay: index * .06 }} className="project-preview" key={project.title}><div className="project-preview__image"><Image src={project.image} alt={project.title} fill sizes="(max-width: 780px) 100vw, 33vw" /></div><div className="project-preview__body"><span>{project.category} · {project.location}</span><h3>{project.title}</h3><p>{project.description}</p><Link href="/projects" aria-label={`View ${project.title}`}><MoveUpRight size={19} /></Link></div></motion.article>)}</div></div></section>

    <section className="section insights-home"><div className="shell"><SectionIntro eyebrow="Learn with us" title={<>Energy & electrical <em>insights.</em></>} description="Helpful, plain-language guidance for better energy and electrical choices." action={{ label: "All insights", href: "/insights" }} /><div className="insight-grid">{insights.map((insight, index) => <motion.article {...fadeUp} transition={{ duration: .5, delay: index * .06 }} className="insight-card" key={insight.title}><div className="insight-card__image"><Image src={insight.image} alt="" fill sizes="(max-width: 780px) 100vw, 33vw" /></div><div><span>{insight.category} <i /> {insight.readingTime}</span><h3>{insight.title}</h3><p>{insight.description}</p><Link className="card-link" href="/insights">Read article <ChevronRight size={16} /></Link></div></motion.article>)}</div></div></section>

    <section className="section process-section"><div className="shell"><SectionIntro eyebrow="How we work" title={<>A clear path to <em>reliable power.</em></>} /><ol className="process-grid">{[['01', 'Tell us what you need', 'Share your electrical or energy requirements with our team.'], ['02', 'Get professional advice', 'We assess the need and recommend a suitable, practical direction.'], ['03', 'Installation & implementation', 'Our qualified team brings the plan carefully into action.'], ['04', 'Ongoing support', 'We remain available for care, maintenance, and future improvements.']].map(([number, title, copy]) => <motion.li {...fadeUp} key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></motion.li>)}</ol></div></section>

    <section className="section testimonials-section"><div className="shell testimonials-layout"><div><span className="eyebrow">Customer stories</span><h2>What our customers <em>will say.</em></h2><p>We are preparing this space for verified customer reviews. Until then, we prefer not to present invented testimonials as real customer feedback.</p></div><div className="testimonial-placeholder"><Quote size={34} /><p>“A verified customer story will appear here once the customer has agreed to share it.”</p><span>Customer testimonial placeholder</span></div></div></section>

    <section className="section cta-section"><div className="shell cta-panel"><div><span className="eyebrow eyebrow--lime">Let&apos;s get started</span><h2>Ready to power <em>your future?</em></h2><p>Tell us about your project and we&apos;ll help you find the right next step.</p></div><div className="cta-panel__actions"><Link href="/request-quote" className="button button--lime">Get a quote <ArrowRight size={17} /></Link><Link href="/contact" className="button button--glass">Contact us</Link></div></div></section>
  </PageMotion>
}
